### ISSUE TITLE
VMware Fusion does not install via brew cask

### ISSUE THREAD

**Issue by takashiyoshida** [takashiyoshida/my-boxen#1]
During the installation of VMware Fusion via brew cask, the following error message appears.

```
Error: Execution of 'brew cask install vmware-fusion --appdir=/Applications' returned 1: ==> Downloading https://download3.vmware.com/software/fusion/file/VMware-Fusion-7.1.2-2779224.dmg
==> Symlinking App 'VMware Fusion.app' to '/Applications/VMware Fusion.app'
Error: Permission denied - /usr/local
==> Symlinking Binary 'ovftool' to '/usr/local/bin/ovftool'

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:556:in `mkpath'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/artifact/symlinked.rb:11:in `create_filesystem_link'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/artifact/symlinked.rb:64:in `link'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/artifact/symlinked.rb:87:in `block in install_phase'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/artifact/symlinked.rb:87:in `each'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/artifact/symlinked.rb:87:in `install_phase'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/artifact/binary.rb:3:in `install_phase'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/installer.rb:119:in `block in install_artifacts'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/installer.rb:117:in `each'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/installer.rb:117:in `install_artifacts'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/installer.rb:66:in `install'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/cli/install.rb:17:in `each'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/cli/install.rb:17:in `install_casks'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/cli/install.rb:6:in `run'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/cli.rb:79:in `run_command'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/cli.rb:119:in `process'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/brew-cask-cmd.rb:18:in `<main>'
Error: /Stage[main]/People::Takashiyoshida::Applications/Package[vmware-fusion]/ensure: change from absent to present failed: Execution of 'brew cask install vmware-fusion --appdir=/Applications' returned 1: ==> Downloading https://download3.vmware.com/software/fusion/file/VMware-Fusion-7.1.2-2779224.dmg
==> Symlinking App 'VMware Fusion.app' to '/Applications/VMware Fusion.app'
Error: Permission denied - /usr/local
==> Symlinking Binary 'ovftool' to '/usr/local/bin/ovftool'

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:556:in `mkpath'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/artifact/symlinked.rb:11:in `create_filesystem_link'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/artifact/symlinked.rb:64:in `link'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/artifact/symlinked.rb:87:in `block in install_phase'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/artifact/symlinked.rb:87:in `each'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/artifact/symlinked.rb:87:in `install_phase'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/artifact/binary.rb:3:in `install_phase'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/installer.rb:119:in `block in install_artifacts'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/installer.rb:117:in `each'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/installer.rb:117:in `install_artifacts'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/installer.rb:66:in `install'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/cli/install.rb:17:in `each'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/cli/install.rb:17:in `install_casks'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/cli/install.rb:6:in `run'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/cli.rb:79:in `run_command'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/hbc/cli.rb:119:in `process'
/opt/boxen/homebrew/Cellar/brew-cask/0.54.1/rubylib/brew-cask-cmd.rb:18:in `<main>'
```

**Comment by takashiyoshida** [comment]
I'm closing this issue because I no longer install OS X applications via brew cask.
